name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Installer Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"  # Choisissez la version Python que vous utilisez

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 4 : Lancer les tests unitaires
    - name: Run unit tests
      run: |
        pytest tests/

    # Étape 5 : Vérification du formatage avec flake8
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .